<cfoutput>
	#html.checkbox(
		id=field.getCSSID(),
		name=field.getName(),
		value=field.getDefaultValue(),
		label=Field.getLabel(),
		required=Field.getIsRequired(),
		size=Field.getMaxLength,
		class=Field.getCSSClass()
	)#
</cfoutput>